### ISSUE TITLE
sql files missing during initital setup

### ISSUE THREAD

**Issue by wsirhc** [haiwen/seafile-rpi#103]
Due to the deletion of the sql copy job in the build-server.py.patch file, the setup-seafile-sql.sh script runs into an error when creating the database tables. The sql files are just missing.

Is there a reason why these lines have been removed?
```
 # copy sql scripts
-    sql_scriptsdir = os.path.join(scripts_srcdir, 'sql')
-    dst_sql_scriptsdir = os.path.join(serverdir, 'sql')
-    try:
-        shutil.copytree(sql_scriptsdir, dst_sql_scriptsdir)
-    except Exception as e:
-        error('failed to copy sql scripts: %s' % e)
```
-

**Comment by Gustl22** [comment]
Thx.
See https://github.com/haiwen/seahub/pull/5073#issuecomment-1005545655
I'll rewrite the relevant section.
