### ISSUE TITLE
Upgrade to 9.0.2 fails

### ISSUE THREAD

**Issue by nihilistaX** [haiwen/seafile-rpi#106]
I tried to upgrade from 8.0.7 to 9.0.2 and got this error: 

````
Error processing line 1 of /root/.local/lib/python3.7/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.7/site.py", line 174, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'ensure_shim'
````

**Comment by nihilistaX** [comment]
Strange, now i backuped and deleted my config, did a complete new install of seafile, then reintegrated my old config files and db.
Now seafile starts and seams to work correct.

**Comment by jobenvil** [comment]
Strange I have never seen such error. Good that you solved by yourself!. Closing.
