### ISSUE TITLE
wsgidav requires markupsafe==2.0.1

### ISSUE THREAD

**Issue by wsirhc** [haiwen/seafile-rpi#113]
The 9.0.4 build script uses markupsafe version > 2.0.1
This leads to an error on running wsgidav and so webdav is not working.

The error in controller.log is:
` importError: cannot import name ‘soft_unicode’ from ‘markupsafe’ (/home/seafile/seafile-server-9.0.4/seahub/thirdpart/markupsafe/init.py)`

Please update the requirements.txt to `markupsafe==2.0.1` .

Reference: 
https://forum.seafile.com/t/seafile-community-edition-9-0-4-is-ready/15988/20

**Comment by jobenvil** [comment]
@wsirhc since the script is not only for `v9.0.4`, make it sense to stick forever to `markupsafe==2.0.1`? [Source.](https://github.com/pallets/markupsafe/issues/284)
