### ISSUE TITLE
version GLIBC_2.15/17 not found

### ISSUE THREAD

**Issue by jhonny-oliveira** [haiwen/seafile-rpi#12]
I'm getting this error on Raspbian GNU/Linux 7 (wheezy) version 7.8 (latest updates) with seafile-server version 5.0.4. There was no such problem before with version 5.0.3. 

/<myFullPath>/seafile-server-5.0.4/seafile/bin/seafile-controller: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.15' not found (required by /<myFullPath>/seafile-server-5.0.4/seafile/lib/libevent-2.0.so.5)
/<myFullPath>/seafile-server-5.0.4/seafile/bin/seafile-controller: /lib/arm-linux-gnueabihf/libc.so.6: version`GLIBC_2.17' not found (required by /<myFullPath>/seafile-server-5.0.4/seafile/lib/libevent-2.0.so.5)
/<myFullPath>/seafile-server-5.0.4/seafile/bin/seafile-controller: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.15' not found (required by /<myFullPath>/seafile-server-5.0.4/seafile/lib/libglib-2.0.so.0)
/<myFullPath>/seafile-server-5.0.4/seafile/bin/seafile-controller: /lib/arm-linux-gnueabihf/libc.so.6: version`GLIBC_2.17' not found (required by /<myFullPath>/seafile-server-5.0.4/seafile/lib/libglib-2.0.so.0)

Thanks!

**Comment by focmb** [comment]
same issue here on my raspberry 2 when I did the upgrade from 5.0.3 to 5.0.4

**Comment by abysso2** [comment]
Hi,
the main difference is, that the 5.0.3 was built by jobenvil on a bananapi / weezy and i built the 5.0.4 on a cubietruck / jessie.

So, i compiled the package with

 libc6-dev:armhf                   2.19-18+deb8u1

Seems, that there an some things about comatibility to be cleared - i will investigate at the upcoming weekend.

Regards,
Andreas

**Comment by jobenvil** [comment]
Updated R5.0.4 packages to work since Wheezy

**Comment by 0x6d64** [comment]
Works like a charm for me, thank you a lot!

**Comment by focmb** [comment]
Works. Thanks.
