### ISSUE TITLE
Unable to start seafile

### ISSUE THREAD

**Issue by jhonny-oliveira** [haiwen/seafile-rpi#13]
I'm unable to start seafile, I get the following error:

./seafile.sh: line 73: 19463 Illegal instruction     LD_LIBRARY_PATH=$SEAFILE_LD_LIBRARY_PATH ${seaf_controller} --test -c "${default_ccnet_conf_dir}" -d "${seafile_data_dir}" -F "${central_config_dir}"

**Comment by jobenvil** [comment]
hi Jhonny, which release do you use? Last 5.0.5 oder older

**Comment by jhonny-oliveira** [comment]
Sorry.

Just installed 5.0.5. Version 5.0.4 was running just fine.
In case it is required, you can find further details about my setup on the
previous incident I have also opened for 5.0.4.​

Best regards,
Jhonny Oliveira

**Comment by jobenvil** [comment]
@abysso2 ummh!

Voilá, hopefully we run once again not in same problems. Check please this one and let me know:
[seafile-server_5.0.5_pi.tar.gz](https://github.com/haiwen/seafile-rpi/files/156382/seafile-server_5.0.5_pi.tar.gz)

Sorry for the inconvenients Jhonny!

**Comment by jobenvil** [comment]
There is something new to consider for the seahub_settings.py if you run Seafile in non-root modus. There are more infos in the forum. Search the announcement from Daniel Pan regarding R5.0.5. Maybe is this your issue.

**Comment by abysso2** [comment]
Ok, i always start seafile as root - so no issues here. 

@ jobenvil: Can you reproduce the issue here?

Regards,
Andreas

**Comment by jobenvil** [comment]
@abysso2 Unfortunately not. I had broke my banana (trying to fix it right now) where it runs my seafile server. Only where I usually compile Seafile versions, raspberry pi, is running fine. Let's check Jhonny my given compiled version, which in fact I didn't tested (but is compilated, like as usuall, with same cooked script)

BTW, you can wait to announce in the forum the new 5.0.5 Release until this issue is cleared.

**Comment by fmirkes** [comment]
I had the same problem as jhonny on a Raspberry Pi Model B.
The new build from @jobenvil fixed it for me.

**Comment by Jonas16** [comment]
Same here. The new build works now on my Raspberry Pi B+

**Comment by draptik** [comment]
:+1:  @jobenvil Thanks!
Note: I never run seafile as root. The provided build works also for non-root user.

**Comment by jobenvil** [comment]
@abysso2 I will upload the new build like "official"

**Comment by jobenvil** [comment]
Added new tag to official download link to difference it with prior build.

**Comment by jhonny-oliveira** [comment]
I also confirm it is working again.
Thanks.
