### ISSUE TITLE
build.sh script can't clone https://www.github.com/haiwen/libevhtp.git

### ISSUE THREAD

**Issue by wsirhc** [haiwen/seafile-rpi#131]
Don't know if it is an issue of the build.sh script, but the libevhtp.git Repo is the only one that throws an error while cloning:

```
-> [5/14] Build libevhtp

+ git clone https://www.github.com/haiwen/libevhtp.git
Cloning into 'libevhtp'...
fatal: unable to access 'https://www.github.com/haiwen/libevhtp.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
 ```

The script is executed inside a Dockerfile with debian:bullseye. CURL and GNUTLS-BIN Packages have been updated.

Any idea what to do to get the cloning to work?

**Comment by freeplant** [comment]
We have updated the instruction for building Seafile community edition on Raspberry Pi or other platforms: [Raspberry Pi - Seafile Admin Manual](https://manual.seafile.com/build_seafile/rpi/) . This build.sh script is no longer used.
