### ISSUE TITLE
File does not exist 

### ISSUE THREAD

**Issue by focmb** [haiwen/seafile-rpi#16]
The error message "File does not exist" is shown when I try to open a file in the webinterface with white spaves in the path name.

Seafile Server CE 6.0.6 on Raspberry Pi 3 with Apache 2.4 as Reverse Proxy and Seafile as non-root-subdomain.

**Comment by jobenvil** [comment]
@focmb what kind of file did you try to open? I opened many files -with whitespaces- and was working like as usual.

**Comment by focmb** [comment]
I tried to open different pdf files and now some other file types (txt, m3u, pls, ...) in encrypted and non encrypted libraries. If the file name or the library name consists a white space the file can not be opened --> File does not exist. I think this is an issue for the apache web server. I use apache 2.4.10.

In the Seafile server manual I found:

    Troubleshooting
    ------------------
    Problems with paths and files containing spaces

    If there are problems with paths or files containing spaces, make sure to have at least Apache 2.4.12.

    References
    -------------
    https://github.com/haiwen/seafile/issues/1258#issuecomment-188866740
    https://bugs.launchpad.net/ubuntu/+source/apache2/+bug/1284641
    https://bugs.launchpad.net/ubuntu/+source/apache2/+bug/1284641/comments/5
    https://svn.apache.org/viewvc/httpd/httpd/tags/2.4.12/CHANGES?view=markup#l45

For my raspberry only apache 2.4.10 is avaliable. So I have to wait for a new apache version to solve this problem.

**Comment by jobenvil** [comment]
>  For my raspberry only apache 2.4.10 is avaliable. So I have to wait for a new apache version to solve this problem.

Unfortunately yes. But what about to change to stretch/testing branch? It could be a possibility.

**Comment by Rotzbua** [comment]
Or use backport branch from official debian.

**Comment by focmb** [comment]
My raspberry works as web server with more than gogs as a service. thatswhy I will only use the stable branch.

I solved the problem with Nginx. I switched from Apache to Nginx and now Seafile is worling flawless.

**Comment by jobenvil** [comment]
Thanks @Rotzbua and @focmb for reporting.
