### ISSUE TITLE
If it's possible to create seafile docker image for RPi?

### ISSUE THREAD

**Issue by yangxuan8282** [haiwen/seafile-rpi#17]
I want to write Dockerfile myself, but have no clue how to do it.
The official seafile docker ([haiwen/seafile-docker](https://github.com/haiwen/seafile-docker)) is kind of mess, with a bunch of scripts. The preferred way to deploy docker should be non-interactive.

**Comment by yangxuan8282** [comment]
seems build a seafile docker for RPi is pretty straight forward
with Dockerfile from [VGoshev/seafile-docker](https://github.com/VGoshev/seafile-docker), just replace base  image will works, I have pushed the docker image to docker hub: [yangxuan8282/rpi-alpine-seafile](https://hub.docker.com/r/yangxuan8282/rpi-alpine-seafile/)

**Comment by jobenvil** [comment]
@yangxuan8282 , thanks for the links
