### ISSUE TITLE
Unhandled Exception after upgrading 6.0.9 -> 6.1.0

### ISSUE THREAD

**Issue by ghost** [haiwen/seafile-rpi#18]
Hello,
I get this error on my web Browser since the upgrade :
"Unhandled Exception 
An unhandled exception was thrown by the application."

Plateform : RaspberryPi 1
How to overcome this ? Or how to go back to the previous version ?
Thanks.

**Comment by jobenvil** [comment]
Can you please specify the upgrade procedure? Will be nice if you copy and paste the steps. For this, check the `history` file in your raspberry pi.

A good start is to check seafile and nginx log files

Clarify as well:
- Start Release

**Comment by Feranor** [comment]
I got the same error; rolled back to 6.0.9 by running the minor update script in the seafile-server-6.0.9 folder.

**Comment by ghost** [comment]
Sure, here it is. Hope I didn't miss anything...
ffmpeg failed because it doesn't exist for RPi.
seafile-restart.sh and seafile-reload.sh are script I made for cron tasks.

624 wget https://github.com/haiwen/seafile-rpi/releases/download/v6.1.0/seafile-server_6.1.0_beta_pi.tar.gz
  625  ls
  626  tar -xvzf seafile-server_6.1.0_beta_pi.tar.gz
  627  ls
  628  sudo apt-get install ffmpeg
  629  cd seafile-server-latest
  630  ls
  631  ./seahub.sh stop
  632  ./seafile.sh stop
  633  cd ..
  634  cd seafile-server-6.1.0
  635  ls
  636  ls upgrade/upgrade_*
  637  ./upgrade/upgrade_6.0_6.1.sh
  638  cd ..
  639  ls
  640  cd ..
  641  ls
  642  cd cron
  643  ls
  644  ./seafile-restart.sh
  645  top
  646  ls
  647  ./seafile-reload.sh
  648  cat seafile-restart.sh
  649  /home/pi/cloud/seafile-server-latest/seafile.sh start
  650  /home/pi/cloud/seafile-server-latest/seahub.sh start-fastcgi
  651  sudo reboot now

**Comment by ghost** [comment]
Nginx seems to work well as it displays the welcome message in my web browser while Seafile is not running. 
Seafile.sh task starts fine, but seahub.sh failed to start.

**/var/log/nginx/error.log**
`2017/05/12 20:45:46 [error] 1424#0: *170 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.254, server: XXXXXXXX, request: "GET /seafhttp/repo/7336a451-ae5e-4da8-8c9a-8d93ec3983d6/commit/HEAD HTTP/1.1", upstream: "http://127.0.0.1:8082/repo/7336a451-ae5e-4da8-8c9a-8d93ec3983d6/commit/HEAD", host: "XXXXXXXX"`

**/var/log/nginx/seahub.access.log**
```
192.168.0.254 - - [12/May/2017:20:39:37 +0200] "GET / HTTP/1.1" 200 185 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30"
192.168.0.254 - - [12/May/2017:20:39:56 +0200] "GET / HTTP/1.1" 200 185 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0"
192.168.0.254 - - [12/May/2017:20:39:56 +0200] "GET /favicon.ico HTTP/1.1" 200 185 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0"
192.168.0.254 - - [12/May/2017:20:40:43 +0200] "GET /api2/account/info/ HTTP/1.1" 200 185 "-" "Mozilla/5.0"
192.168.0.254 - - [12/May/2017:20:40:43 +0200] "GET /api2/ping/ HTTP/1.1" 200 185 "-" "Mozilla/5.0"
192.168.0.254 - - [12/May/2017:20:42:30 +0200] "GET /api2/ping/ HTTP/1.1" 200 185 "-" "Mozilla/5.0"
192.168.0.254 - - [12/May/2017:20:42:30 +0200] "GET /api2/account/info/ HTTP/1.1" 200 185 "-" "Mozilla/5.0"
192.168.0.254 - - [12/May/2017:20:43:45 +0200] "GET /api2/unseen_messages/ HTTP/1.1" 200 185 "-" "Mozilla/5.0"

```
**/var/log/nginx/seahub.error.log**
```
2017/05/12 20:42:30 [error] 1427#0: *333 FastCGI sent in stderr: "" while reading response header from upstream, client: 192.168.0.254, server: XXXXXXXXXX, request: "GET /api2/account/info/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:8000", host: "XXXXXXXXXX"
2017/05/12 20:42:30 [error] 1427#0: *333 FastCGI sent in stderr: "Traceback (most recent call last):
  File "/home/pi/cloud/seafile-server-6.1.0/seahub/thirdpart/flup-1.0.2-py2.7.egg/flup/server/fcgi_base.py", line 558, in run
    protocolStatus, appStatus = self.server.handler(self)
  File "/home/pi/cloud/seafile-server-6.1.0/seahub/thirdpart/flup-1.0.2-py2.7.egg/flup/server/fcgi_base.py", line 1118, in handler
    result = self.application(environ, start_response)
  File "/home/pi/cloud/seafile-server-6.1.0/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/core/handlers/wsgi.py", line 170, in __call__
    self.load_middleware()
  File "/home/pi/cloud/seafile-server-6.1.0/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/core/handlers/base.py", line 52, in load_middleware
    mw_instance = mw_class()
  File "/home/pi/cloud/seafile-server-6.1.0/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/middleware/locale.py", line 24, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "/home/pi/cloud/seafile-server-6.1.0/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/core/urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/pi/cloud/seafile-server-6.1.0/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/core/urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/pi/cloud/seafile-server-6.1.0/seahub/seahub/utils/rooturl.py", line 41, in <module>
    (r'^%s' % settings.SITE_ROOT[1:], include(settings.SITE_ROOT_URLCONF)),
  File "/home/pi/cloud/seafile-server-6.1.0/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/pi/cloud/seafile-server-6.1.0/seahub/seahub/urls.py
```

**Comment by jobenvil** [comment]
it looks good, only the rights must be considered. You should change the user and group rights because I suppose you have the default one after the extraction with `tar`. Do a `chown -R seafile:nogroup seafile-server-6.1.0`


Here is like it looks like in my odroidXU4, where Seafile Server works:

```
root@hiperborea /media/sda/seafile # ll
total 80020
drwx------ 8 seafile nogroup     4096 Mai 23  2016 seafile-data
drwxrwxr-x 2 seafile seafile     4096 Mai 23  2016 logs
drwxr-xr-x 4 seafile nogroup     4096 Mai 24  2016 seahub-data
drwx------ 2 seafile nogroup     4096 Sep 18  2016 conf
drwxr-xr-x 6 seafile nogroup     4096 Feb 17 12:25 seafile-server-6.0.8
-rwxrw-r-- 1 root    root    25857759 Feb 17 12:55 seafile-server_6.0.8_pi.tar.gz
drwxr-xr-x 6 seafile nogroup     4096 Apr  6 18:50 seafile-server-6.0.9
-rw-r--r-- 1 root    root    25862197 Apr  6 18:55 seafile-server_6.0.9_pi.tar.gz
drwxr-xr-x 6 seafile nogroup     4096 Mai 11 17:58 seafile-server-6.1.0
-rwxr-xr-x 1 root    root    30177445 Mai 11 18:04 seafile-server_6.1.0_pi.tar.gz
lrwxrwxrwx 1 seafile seafile       20 Mai 11 18:09 seafile-server-latest -> seafile-server-6.1.0
drwx------ 3 seafile nogroup     4096 Mai 11 18:10 ccnet
drwxrwxr-x 2 seafile seafile     4096 Mai 11 18:10 pids
root@hiperborea /media/sda/seafile # uname -a
```


 The build environment is a raspberry Pi B+ (`Linux thor 4.9.25+ #994 Fri Apr 28 16:46:40 BST 2017 armv6l GNU/Linux`). In my case `ffmpeg` is there:


```
desigual@thor ~ $ sudo  apt-get install ffmpeg
Reading package lists... Done
Building dependency tree
Reading state information... Done
ffmpeg is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

```

**Comment by ghost** [comment]
I'll try to check for a rights issue. 

About ffmpeg I get that :
```
sudo apt-get install ffmpeg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package ffmpeg is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ffmpeg' has no installation candidate
```

**Comment by nscuro** [comment]
@jobenvil I have the same issue, I posted it in the [forum thread](https://forum.seafile.com/t/seafile-server-6-1-0-beta-for-raspberry-pi-is-ready-12-05-2017/2770/2?u=nscuro).

@jbsapis Regarding ffmpeg: It was deprecated in Raspbian / Debian and replaced with a fork, avconv. It being a fork, the commands are basically the same, for more info see [this reddit thread](https://www.reddit.com/r/raspberry_pi/comments/48eo83/ffmpeg_for_raspbian_jessie/).

In short, execute `sudo apt install libav-tools`, then add `alias ffmpeg=avconv` to your `/etc/profile`. When you log in again, everything should be just as if you actually installed ffmpeg.

**Edit:** Output of `ls -la` in the `seafile`-directory:
```
total 488
drwxr-xr-x 12 seafile seafile   4096 May 12 18:48 .
drwxr-xr-x  4 root    root      4096 Apr 12  2016 ..
-rw-------  1 seafile seafile   8521 May 12 19:33 .bash_history
-rw-r--r--  1 seafile seafile    220 Apr 12  2016 .bash_logout
-rw-r--r--  1 seafile seafile   3512 Apr 12  2016 .bashrc
drwx------  6 seafile seafile   4096 May 12 19:55 ccnet
drwx------  2 seafile seafile   4096 Dec 28 21:10 conf
drwx------  3 seafile seafile   4096 Dec 28 16:37 .config
drwxr-xr-x  2 seafile seafile   4096 May 12 18:48 .imageio
drwxr-xr-x  2 seafile seafile   4096 May 12 18:44 installed
drwxr-xr-x  2 seafile seafile   4096 Apr 12  2016 logs
drwxr-xr-x  2 seafile seafile   4096 May 12 19:55 pids
-rw-r--r--  1 seafile seafile    675 Apr 12  2016 .profile
drwxr-xr-x  6 seafile seafile   4096 Apr  6 18:50 seafile-server-6.0.9
drwxr-xr-x  6 seafile seafile   4096 May 11 17:58 seafile-server-6.1.0
lrwxrwxrwx  1 seafile seafile     20 May 12 18:47 seafile-server-latest -> seafile-server-6.1.0
drwxr-xr-x  4 seafile seafile   4096 Apr 13  2016 seahub-data
-rw-r--r--  1 seafile seafile 421888 May 12 18:47 seahub.db
```

**Comment by jobenvil** [comment]
@nscuro completely right and no issue with your directory. It looks like some dependency issue with Django 1.8.18 (LTS), which was updated indeed from 1.8.17. Strange is in my case that I build up on Debian Wheezy to enable compatibility backwards and installed -like as usual- into my odroidXU4 (Ubuntu) .

What about these?

```
960 sudo pip install --upgrade pip
961 sudo pip install pillow moviepy
```

**Comment by nscuro** [comment]
@jobenvil 
```
scuro@scuro-rpi:/home/seafile $ sudo pip install --upgrade pip
Downloading/unpacking pip from https://pypi.python.org/packages/b6/ac/7015eb97dc749283ffdec1c3a88ddb8ae03b8fad0f0e611408f196358da3/pip-9.0.1-py2.py3-none-any.whl#md5=297dbd16ef53bcef0447d245815f5144
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Installing collected packages: pip
  Found existing installation: pip 1.5.6
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed pip
Cleaning up...
scuro@scuro-rpi:/home/seafile $ sudo pip install pillow moviepy
Requirement already satisfied: pillow in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: moviepy in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: olefile in /usr/local/lib/python2.7/dist-packages (from pillow)
Requirement already satisfied: imageio==2.1.2 in /usr/local/lib/python2.7/dist-packages (from moviepy)
Requirement already satisfied: tqdm==4.11.2 in /usr/local/lib/python2.7/dist-packages (from moviepy)
Requirement already satisfied: numpy in /usr/lib/python2.7/dist-packages (from moviepy)
Requirement already satisfied: decorator==4.0.11 in /usr/local/lib/python2.7/dist-packages (from moviepy)
```

**Comment by nscuro** [comment]
To be honest I'm not completely sure how the dependency-stuff with seahub works anyway. Some are distributed with it, some must be installed manually.

```
scuro@scuro-rpi:/home/seafile/seafile-server-latest/seahub/thirdpart $ ls -1
captcha
chardet-2.3.0-py2.7.egg
chardetect
Django-1.8.16-py2.7.egg
Django-1.8.17-py2.7.egg
Django-1.8.18-py2.7.egg
django-admin
django-admin.py
django_appconf-1.0.1-py2.7.egg
django_compressor-1.4-py2.7.egg
django_constance-1.0.1-py2.7.egg
django_picklefield-0.3.2-py2.7.egg
django_post_office-2.0.6-py2.7.egg
djangorestframework-3.3.2-py2.7.egg
django_statici18n-1.1.3-py2.7.egg
easy-install.pth
et_xmlfile-1.0.1-py2.7.egg
flup-1.0.2-py2.7.egg
gunicorn
gunicorn-19.4.5-py2.7.egg
gunicorn_django
gunicorn_paster
jdcal-1.2-py2.7.egg
jsonfield-1.0.3-py2.7.egg
openpyxl-2.3.0-py2.7.egg
python_dateutil-1.5-py2.7.egg
pytz-2016.1-py2.7.egg
registration
seafobj
shibboleth
site.py
site.pyc
six-1.10.0-py2.7.egg
six-1.9.0-py2.7.egg
termsandconditions
wsgidav
```

```
scuro@scuro-rpi:/home/seafile/seafile-server-latest/seahub/thirdpart $ sudo pip list --format=columns
Package          Version
---------------- -------
chardet          2.3.0
colorama         0.3.2
decorator        4.0.11
gpiozero         1.3.2
html5lib         0.999
imageio          2.1.2
lxkeymap         0.1
mcpi             0.1.1
moviepy          0.2.3.2
ndg-httpsclient  0.3.2
numpy            1.8.2
olefile          0.44
picamera         1.13
pifacecommon     4.2.1
pifacedigitalio  3.1.0
Pillow           4.1.1
pip              9.0.1
pyasn1           0.1.7
pygame           1.9.2a0
pygobject        3.14.0
pyOpenSSL        0.13.1
pyserial         2.6
python-dateutil  2.2
python-ldap      2.4.10
python-memcached 1.58
requests         2.14.2
RPi.GPIO         0.6.3
RTIMULib         7.2.1
sense-hat        2.2.0
setuptools       5.5.1
six              1.8.0
spidev           3.0
tqdm             4.11.2
urllib3          1.19.1
virtualenv       1.11.6
wheel            0.24.0
```
How high is the chance this leads to conflicts? There are multiple versions per dependency in this case.

**Comment by jobenvil** [comment]
> To be honest I'm not completely sure how the dependency-stuff with seahub works anyway. Some are distributed with it, some must be installed manually.

me too as well. In theory all extra stuff what we need for seahub dependencies should be inside thirdpart and others like phyton and so on are communicated by seafile. Are you worrying about Django 1.16, 1.17, 1.18? I Need to clean them (1.16-1.17) from build environment, but only Django 1.18. is called, like we can see in the log files.

**Edit:** @nscuro How you get the second one list? These are not the dependencies inside seahub_thirdpart, isn't it?

**Comment by jobenvil** [comment]
I have on build environment:
```
desigual@thor ~/env_seafile/dev/seahub_thirdpart $ pip list --format=columns
Package          Version
---------------- ------------
decorator        4.0.11
distribute       0.6.24dev-r0
imageio          2.1.2
iotop            0.4.4
moviepy          0.2.3.2
MySQL-python     1.2.3
numpy            1.6.2
olefile          0.44
picamera         1.10
pifacecommon     4.1.2
pifacedigitalio  3.0.4
PIL              1.1.7
Pillow           4.1.1
pip              9.0.1
pyserial         2.5
python-memcached 1.48
RPi.GPIO         0.6.2
setuptools       0.6rc11
simplejson       2.5.2
six              1.1.0
tqdm             4.11.2
uncompyle2       1.1
urllib3          1.3
```
and the really brought by seahub thirdpart:

```
desigual@thor ~/env_seafile/dev/seahub_thirdpart $ cat easy-install.pth
import sys; sys.__plen = len(sys.path)
./pytz-2016.1-py2.7.egg
./django_statici18n-1.1.3-py2.7.egg
./django_appconf-1.0.1-py2.7.egg
./djangorestframework-3.3.2-py2.7.egg
./django_compressor-1.4-py2.7.egg
./jsonfield-1.0.3-py2.7.egg
./django_post_office-2.0.6-py2.7.egg
./gunicorn-19.4.5-py2.7.egg
./flup-1.0.2-py2.7.egg
./chardet-2.3.0-py2.7.egg
./python_dateutil-1.5-py2.7.egg
./six-1.9.0-py2.7.egg
./django_picklefield-0.3.2-py2.7.egg
./django_constance-1.0.1-py2.7.egg
./jdcal-1.2-py2.7.egg
./et_xmlfile-1.0.1-py2.7.egg
./openpyxl-2.3.0-py2.7.egg
./Django-1.8.18-py2.7.egg
import sys; new=sys.path[sys.__plen:]; del sys.path[sys.__plen:]; p=getattr(sys,'__egginsert',0); sys.path[p:p]=new; sys.__egginsert = p+len(new)

```

**Comment by nscuro** [comment]
Not only Django. For example, `six` and `python-dateutils` are provided by Seahub and installed via pip (in different versions, of course). A quick Google search did not result in any answer as to how python resolves dependencies in this kind of situation.

The strange thing is that exactly this error has been [reported before](https://forum.seafile.com/t/fresh-install-unhandled-exception/1590), but back then the solution was to simply install `python-urllib3`. I tried to manually update this dependency to the newest one available, but it didn't help.

**Comment by jobenvil** [comment]
> Not only Django. For example, six and python-dateutils are provided by Seahub and installed via pip (in different versions, of course). A quick Google search did not result in any answer as to how python resolves dependencies in this kind of situation.

IMHO the Django dependency will be first checked to the eggs in seahub_thirdpart directory and if not there to search in the python system dependencies. If it is not on both, we get these kind of errors like in `/var/log/nginx/seahub.error.log`

**Edit:** Usually the problematic module is given at the end of the traceback call:

  ```
File "/home/pi/cloud/seafile-server-6.1.0/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/pi/cloud/seafile-server-6.1.0/seahub/seahub/urls.py
```

**Comment by jobenvil** [comment]
@nscuro Here are my phyton system dependencies on the seafile server works:

```
root@hiperborea /media/sda/seafile # pip list --format=columns
Package          Version
---------------- -----------
attrs            15.2.0
chardet          2.3.0
configobj        5.0.6
cryptography     1.2.3
decorator        4.0.11
dnspython        1.12.0
docopt           0.6.2
enum34           1.1.2
gyp              0.1
idna             2.0
imageio          2.1.2
ipaddress        1.0.16
Landscape-Client 16.3+bzr834
moviepy          0.2.3.2
mysqlclient      1.3.7
ndg-httpsclient  0.4.0
ngxtop           0.0.2
numpy            1.12.1
PAM              0.4.2
Pillow           3.1.2
pip              9.0.1
pyasn1           0.1.9
pyasn1-modules   0.0.7
pycrypto         2.6.1
pyOpenSSL        0.15.1
pyparsing        2.1.1
pyserial         3.0.1
python-apt       1.1.0b1
python-debian    0.1.27
python-memcached 1.53
requests         2.9.1
service-identity 16.0.0
setuptools       20.7.0
simplejson       3.8.1
six              1.10.0
tabulate         0.7.5
tqdm             4.11.2
Twisted          16.0.0
urllib3          1.13.1
wheel            0.29.0
zope.interface   4.1.3

```

**Comment by nscuro** [comment]
> Usually the problematic module is given at the end of the traceback call

Yup, but either I just fail to see / understand it or this does not state what exactly is the problem besides "something went wrong in `/seahub/seahub/urls.py`"

**Comment by jobenvil** [comment]
Can you add `DEBUG = True` to `seahub_settings.py`? maybe we can see more. [Here detailed the process](https://manual.seafile.com/faq/setup.html).

**Edit:** No probably not :-(

**Comment by nscuro** [comment]
@jobenvil No, it does not result in any more information.

I also tried to update `six` & `pyserial`, downgrading `Pillow` to 3.1.2... no difference.

**Comment by jobenvil** [comment]
If you don't mind, I will contact with @lins05 , it could be probably some python dependency outside `seahub_thirdpart`. The only issue are the [requirements.txt](https://github.com/haiwen/seahub/blob/master/requirements.txt) for thirdpart. Strange is that for me it works outside of the build platform =)

**Comment by nscuro** [comment]
The last line in my Traceback is:
`File "/home/seafile/seafile-server-6.1.0/seahub/seahub/urls.py", line 12,`

Line 12 in this file would be here: https://github.com/haiwen/seahub/blob/v6.1.0-server/seahub/urls.py#L12
... not that I understand it, but I noticed in the Traceback of @jbsapis it was missing.

**Edit:** @jobenvil That's a very good idea, looking forward his input on this.

**Comment by framps** [comment]
@jobenvil I don't have any issues on the upgrade because I didn't upgrade until now. But I appreciate you try to get this ugly issue solved !
:+1:

**Comment by jobenvil** [comment]
@framps no issues :-)

@nscuro I see [that on Travis](https://travis-ci.org/haiwen/seahub/builds/222731642) it is installed according to `requirements.txt`:

`pip install -r requirements.txt --allow-all-external --allow-unverified Djblets --allow-unverified PIL`

**Comment by nscuro** [comment]
@jobenvil I executed the same command for the `requirements.txt` in 6.1.0, but it didn't help either.

**Comment by jobenvil** [comment]
> @jobenvil I executed the same command for the requirements.txt in 6.1.0, but it didn't help either.

let's collect information as much as possible. Which Distro do you use and which architecture exactly?. The other user @langhaarschneider, [see closed issue](https://github.com/haiwen/seafile-rpi/issues/19), was using bananian and the upgrade worked for him.

**Comment by nscuro** [comment]
@jobenvil Alright.
```shell
scuro@scuro-rpi:~ $ uname -a
Linux scuro-rpi 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017 armv7l GNU/Linux
```
```shell
scuro@scuro-rpi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie
```

**Comment by jobenvil** [comment]
@nscuro This is a [comparison between yours and mine python module](http://hiperborea.noip.me/seafile/f/3a77888375af40ee95a5/?dl=1)

**Comment by nscuro** [comment]
@jobenvil Thanks, I actually did this yesterday too but didn't see anything obvious. I will try to install some dependencies I'm currently missing completely one after another. Hopefully I can isolate the missing package like that. I'll report back once I'm done.

**Comment by jobenvil** [comment]
I agree, it is not really obvious or maybe something different, therefore I would suggest you to wait until we get feedback from @lins05 

**Edit:** for sure you can follow with this issue, feel free to chose

**Comment by nscuro** [comment]
Yeah... wasn't able to fix it through more or less blindly installing packages. ^^

@jobenvil Which python version do your environments have? I currently have 2.7.9 installed, which is the newest provided by Raspbian it seems. Travis seems to use 2.7.13. 
Technically this should not make any difference as 2.7.x releases are just maintenance- or bugfix-releases, but who knows.

**Comment by jobenvil** [comment]
> @jobenvil Which python version do your environments have? I currently have 2.7.9 installed, which is the newest provided by Raspbian it seems. Travis seems to use 2.7.13.
Technically this should not make any difference as 2.7.x releases are just maintenance- or bugfix-releases, but who knows.

I don't think that it makes any difference between `2.7.*` Mandatory is that python 3.* should not be used.

I compared with [@tjelfe from seafile forum](https://forum.seafile.com/t/seafile-server-6-1-0-beta-for-raspberry-pi-is-ready-12-05-2017/2770/9) and we have following common packages:

```
chardet 		(2.3.0)
decorator        4.0.11
dnspython        1.12.0
imageio          2.1.2
moviepy          0.2.3.2
numpy            1.12.1
pycrypto         2.6.1
pyparsing        2.1.1  or (2.0.3)
python-apt       1.1.0b1 or (0.9.3.12)
python-memcached 1.53
requests         2.9.1 or (2.4.3)
setuptools       20.7.0 or (5.5.1)
simplejson       3.8.1 or (3.6.5)
six              1.10.0 or (1.8.0)
tqdm             4.11.2
urllib3          1.13.1 or (1.9.1)
```

if you are not worried enough...(ironic)

**Edit:** I forgot to tell you which python version I have:
```
root@hiperborea ~ # /usr/bin/python -V
Python 2.7.12
```

**Comment by nscuro** [comment]
Ok, so I'm completely lost now. I think the best is indeed to wait for a dev to look at this. Maybe there are some switches one can use so that the error message will be a bit more detailed or something similar.

**Comment by nscuro** [comment]
I ditched my old system completely and installed `ubuntu MATE 16.04.2`. Following [the manual](https://manual.seafile.com/deploy/using_sqlite.html), I successfully installed your `6.1.0-beta` version. I guess through the MATE-environment there were many python-packages installed already, but maybe this helps for further investigations:

```
astro-pi (1.1.5)
boto (2.38.0)
Cap1xxx (0.1.2)
chardet (2.3.0)
codebug-tether (0.9.1)
configobj (5.0.6)
decorator (4.0.11)
deja-dup-caja (0.0.4)
drumhat (0.0.5)
duplicity (0.7.6)
envirophat (0.0.6)
ExplorerHAT (0.4.2)
folder-color-caja (0.0.79)
folder-color-common (0.0.79)
gpiozero (1.3.1)
imageio (2.1.2)
lockfile (0.12.2)
mate-menu (5.7.1)
mcpi (0.1.1)
microdotphat (0.1.3)
mote (0.0.3)
motephat (0.0.2)
moviepy (0.2.3.2)
netifaces (0.10.4)
numpy (1.11.0)
pantilthat (0.0.2)
pianohat (0.0.5)
picamera (1.12)
picraft (1.0)
piglow (1.2.4)
pigpio (1.30)
Pillow (3.1.2)
pip (8.1.1)
pycrypto (2.6.1)
pygame (1.9.1release)
pygobject (3.20.0)
pyserial (3.0.1)
python-cloudfiles (1.7.10)
python-distutils-extra (2.39)
python-ldap (2.4.22)
python-xlib (0.14)
pyxdg (0.25)
rainbowhat (0.0.1)
requests (2.9.1)
RPi.GPIO (0.6.3)
RTIMULib (7.2.1)
scrollphat (0.0.7)
sense-emu (1.0)
sense-hat (2.2.0)
setuptools (20.7.0)
six (1.10.0)
sn3218 (1.2.6)
spidev (3.0)
st7036 (1.4.3)
tqdm (4.11.2)
urllib3 (1.13.1)
wheel (0.29.0)
wxPython (3.0.2.0)
wxPython-common (3.0.2.0)
youtube-dl (2016.2.22)
Youtube-DLG (0.3.8)
```

The python version is `2.7.12`

```
scuro@scuro-rpi:~$ uname -a
Linux scuro-rpi 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l armv7l armv7l GNU/Linux
```

```
scuro@scuro-rpi:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

I'm sorry that now I cannot continue to help with this issue, but I desperately need my Seafile-instance to be up during the next week. Thank you for your effort @jobenvil, it is greatly appreciated.

**Comment by jobenvil** [comment]
@nscuro I'm the one who has to thank to you for your help and kooperation. You have done tons of efforts on the issue. Highly appreciated your help. I hope that the Ubuntu Mate brings you an step forward.

**Comment by lins05** [comment]
It should be some problem of the newly introduced dependency on moviepy.

In its [README](https://github.com/Zulko/moviepy#installation) it says:
```
 The software FFMPEG should be automatically downloaded/installed (by imageio) during your first use of MoviePy (installation will take a few seconds)
```

But [as some users reported in moviepy's issue tracker](https://github.com/Zulko/moviepy/issues/322#issuecomment-253336571) it doesn't work on rpi:

```
Turns out, no, moviepy does not work entirely normally on the RPi. After discussion in this post, it transpires that the ffmpeg that is downloaded does not work with the RPi. To get the right version, follow these instructions, then it should work fine.
```

About the solutions, for now I guess there are two options:
- First you can follow @nscuro 's comment https://github.com/haiwen/seafile-rpi/issues/18#issuecomment-301162794 
- Or, you can also use this quick fix: edit **the four lines 11 - line 15** in  **seafile-server-6.10.0/seahub/thumbnail/utils.py**, i.e. replace the following lines:

```py
try:
    from moviepy.editor import VideoFileClip
    _ENABLE_VIDEO_THUMBNAIL = True
except ImportError:
    _ENABLE_VIDEO_THUMBNAIL = False
```

With:
```py
_ENABLE_VIDEO_THUMBNAIL = False
``` 
(note there is no leading space)

And restart seahub.

@xiez @imwhatiam  for a real fix, maybe we can disable video previewing on raspberry pi by default?

**Comment by jobenvil** [comment]
> @xiez @imwhatiam for a real fix, maybe we can disable video previewing on raspberry pi by default?

Let's try this workaround with somebody who actually has this problem, to be sure.

**Comment by Captain-Rage** [comment]
I tried the fix proposed by @lins05 but I still got the 'Unhandled Exception' message after restarting Seafile server + Seahub on my Raspberry Pi B+. I hope I was editing the right utils.py file.

EDIT:
@jbsapis @jobenvil : Turns out 'requests' was also needed but wasn't installed. 'pip2 install requests' inside the correct environment did the trick. It's working now!! Thanks for the help!

**Comment by Captain-Rage** [comment]
@jbsapis @jobenvil : Turns out 'requests' was also needed but wasn't installed. 'pip2 install requests' inside the correct environment did the trick. It's working now!! Thanks for the help!

**Comment by leolivier** [comment]
Same issue for me and the only solution I found is disabling the video thumbnail stuff as in the fix proposed by @lins05 which worked for me!
Actually for me the file was: vi seafile-server-6.1.0/seahub/seahub/thumbnail/utils.py (notice seahub twice)

**Comment by jobenvil** [comment]
@leolivier have you tried to install `pip install requests` being `pip` linked to python 2.7 before to apply the fix from @lins05 ?

**Comment by leolivier** [comment]
Yes, I did:
```
>sudo pip2 install requests
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages

```

**Comment by unDocUMeantIt** [comment]
i just ran into the same issue with 6.1.1 on armbian (ubuntu 16.04). finally, this solved it for me:

1. ```echo "ENABLE_VIDEO_THUMBNAIL = False" >> conf/seahub_settings.py```
2. ```sudo apt install python-requests```
3. restart seahub
