### ISSUE TITLE
problems with pip install pillow moviepy

### ISSUE THREAD

**Issue by langhaarschneider** [haiwen/seafile-rpi#19]
The Line
`sudo apt-get install ffmpeg`
worked fine on my bananaPi with bananian Linux - but the Line
`pip install pillow moviepy`
doesn't work. I get some error-messages:
 -   Failed building wheel for pillow
 -   Failed cleaning build dir for numpy
(These are only examples - i get even more...)

Has anyone any ideas?
Everything else seems to work with 6.1beta - seahub and seafile sync with client works even if the pip install failed...
Greetings,

Jonathan

**Comment by jobenvil** [comment]
@langhaarschneider at least it works :-)
try to update pip before.

**Comment by langhaarschneider** [comment]
I just tried that with
`$ pip install --upgrade pip`
`Requirement already up-to-date: pip in /usr/local/lib/python3.4/dist-packages`
Might it be the problem that i also run python 3.4 on my bananaPi - but seafile requires 2.7?

**Comment by langhaarschneider** [comment]
Stackoverflow helped me... http://stackoverflow.com/questions/2812520/pip-dealing-with-multiple-python-versions
`$ sudo pip2.7 install pillow moviepy`
seems to work. Thanks for your help!
