### ISSUE TITLE
Upgrade to 6.1 needs ffmpeg which does not exist on RPi

### ISSUE THREAD

**Issue by leolivier** [haiwen/seafile-rpi#20]
Hi
The installation procedure on the download site for seafile rpi 6.1 beta says that we should install ffmpeg but ffmpeg does not exist on Raspbian...
```
/mnt/ssd/seafile $ sudo apt-get install ffmpeg
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Package ffmpeg is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ffmpeg' has no installation candidate

```
Is there a replacement? (Or should you change the doc for another tool that exist on RPi like avconv ?)

**Comment by jobenvil** [comment]
Hi @leolivier please check the [issue 18](https://github.com/haiwen/seafile-rpi/issues/18) here is described how to

**Comment by leolivier** [comment]
Ok, found the answer in https://github.com/haiwen/seafile-rpi/issues/18 :+1: replaced by avconv
```
sudo apt install libav-tools
alias ffmpeg=avconv

```

**Comment by leolivier** [comment]
Thanks @jobenvil, I found the same solution by myself at the same time you wrote the answer :)
Anyway, you should maybe change the documentation so that we don't have to check the issues to get it working

**Comment by jobenvil** [comment]
@leolivier I usually post the announcement on [Seafile Forum](https://forum.seafile.com/t/seafile-server-6-1-0-beta-for-raspberry-pi-is-ready-12-05-2017/2770) followed with an small installation guide and inputs from other users. Which docu did you read?

**Comment by leolivier** [comment]
@jobenvil : the one here: https://github.com/haiwen/seafile-rpi/releases which says:

```Seafile Server 6.1.0 (Beta) for Raspberry Pi

@jobenvil jobenvil released this 16 days ago · 1 commit to master since this release

6.1.0 beta (2017.05.11)

If you upgrade from 6.0, you need to install ffmpeg package to let the video thumbnail work correctly:

# for ubuntu 16.04
apt-get install ffmpeg
pip install pillow moviepy

```
EDIT: Yes, raspbian is not Ubuntu 16, but there is no information for Raspbian so I tried this one

**Comment by jobenvil** [comment]
@leolivier completely right!

**Comment by jobenvil** [comment]
@leolivier I updated right now the Github reference to consider the forum. Usually this is [just the ChangeLog](https://seacloud.cc/group/3/wiki/server-changelog) which is given by Seafile. Yes, definitely, I have to improve this in order to consider the Seafile Forum. I will think about which is the best way. Comments are wellcome.
