### ISSUE TITLE
How to upgrade safely from 6.0.8 to 6.1.1

### ISSUE THREAD

**Issue by xifi-kif** [haiwen/seafile-rpi#24]
Hi I installed seafile on my Banana PI with armbian image and everything works fine so far with my environment:
```
# uname -a
Linux bpi 4.11.6-sunxi #6 SMP Fri Jun 23 19:56:18 CEST 2017 armv7l armv7l armv7l GNU/Linux
```
```
# lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```
I followed instruction described here https://www.youtube.com/watch?v=4n1d6osMP5c and currently running seafile server 6.0.8 with https.

I'd like to upgrade to the last stable (6.1.1), but I'm not sure how to proceed without breaking everything, since I'm not comfortable with seafile. 

Can you please provide some documentation for upgrading?

**Comment by ocramleznem** [comment]
Hi @xifi-kif 
did you already find this: https://manual.seafile.com/deploy/upgrade.html

**Comment by jobenvil** [comment]
and then, not forgot these:

- Don't forget to **stop Seafile Server** before the upgrade (i.e: `service seafile-server stop` or, another example: `service seahub stop && service seafile stop`)
- Don't forget to change the **directory rights** of Seafile after unpacking it (i.e: `chown -R seafile:nogroup seafile-server-6.1.1` or, another example: `sudo chown -R seafile:seafile seafile-server-6.1.1` )
- Don't forget to apply the **upgrade script/s** according your start release && **with** the **properly user** which **in normal case should be seafile** (i.e change to seafile user: `su - seafile -s /bin/bash` or, another example: `sudo su seafile`)

The script you must apply is: `upgrade_6.0_6.1.sh`

**Comment by jpmaas** [comment]
In this special case, when upgrading to 6.1.x, you also should ensure the following:

- have a running version of ffmpeg or use a fork like avconv using an alias on ffmpeg (see https://github.com/haiwen/seafile-rpi/issues/18#issuecomment-301162794)
- or disable video thumbnails (see https://github.com/haiwen/seafile-rpi/issues/18#issuecomment-310615337)

Note that `sudo apt install python-requests` is a must have for both solutions.

**Comment by xifi-kif** [comment]
Thank you guys for your precious advices. Followed your hints and everything worked smoothly.

Btw I disabled ffmpeg as @HyEnd suggested, since I don't really need that thumbnails' feature and could slow down my device (that is not so fast already).

Thumbs up for seafile and its pi port!
