### ISSUE TITLE
Which filesystem do you recommend? 

### ISSUE THREAD

**Issue by lakano** [haiwen/seafile-rpi#25]
Hi !
I've read SeaFile make a lots of little chunk files on the disk, so could you tell us which filesystem (eg: f2fs) is better on a sd-card for the Pi please?
Best regards,

**Comment by jobenvil** [comment]
If you don't need too much storage place on sd-card I would recommend the samsung evo, for example MicroSDHC 32GB EVO Plus UHS-I Grade 1 Class 10, date: 07/2016 but I would recommend you to put your data on external disk, not inside the sd-card. The filesystem that I'm currently using is ext4 on both, sd-card and external hard drive. The external drive which I would recommend you is e.g. SSD Samsung 850 EVO 500GB, Firmware Revision EMT02B6Q. You can see the [performance of both of them here](https://xu4.keltike.de/performance/odroidxu4-with-and-without-uas-support/)
