### ISSUE TITLE
ccnet-init: No such file or directory

### ISSUE THREAD

**Issue by ikwyl6** [haiwen/seafile-rpi#29]
Hi - I downloaded the 6.2.5 source and running setup-seafile.sh gives this error. Here is my output. I'm using a pogoplug with ARM on arch linux. Anyone have any ideas? The path and file exists for ccnet-init:

`$ ./setup-seafile.sh`
-----------------------------------------------------------------
This script will guide you to config and setup your seafile server.

Make sure you have read seafile server manual at

        https://github.com/haiwen/seafile/wiki

Note: This script will guide your to setup seafile server using sqlite3,
which may have problems if your disk is on a NFS/CIFS/USB.
In these cases, we sugguest you setup seafile server using MySQL.

Press [ENTER] to continue
-----------------------------------------------------------------
Checking packages needed by seafile ...

Checking python on this machine ...
Find python: python2.7

  Checking python module: setuptools ... Done.
  Checking python module: python-imaging ... Done.
  Checking python module: python-sqlite3 ... Done.

Checking for sqlite3 ...Done.

Checking Done.
What would you like to use as the name of this seafile server?
Your seafile users will be able to see the name in their seafile client.
You can use a-z, A-Z, 0-9, _ and -, and the length should be 3 ~ 15
[server name]: alarm

What is the ip or domain of this server?
For example, www.mycompany.com, or, 192.168.1.101

[This server's ip or domain]: 192.168.3.10   

Where would you like to store your seafile data?
Note: Please use a volume with enough free space.
[default: /mnt/wd1000/BTSync/seafile/seafile-data ]

What tcp port do you want to use for seafile fileserver?
8082 is the recommended port.
[default: 8082 ]

This is your config information:

server name:        alarm
server ip/domain:   192.168.3.10
seafile data dir:   /mnt/wd1000/BTSync/seafile/seafile-data
fileserver port:    8082
If you are OK with the configuration, press [ENTER] to continue.

Generating ccnet configuration in /mnt/wd1000/BTSync/seafile/ccnet...

./setup-seafile.sh: line 483: /mnt/wd1000/BTSync/seafile/seafile-server-rpi-source-6.2.5/seafile/bin/ccnet-init: No such file or directory

Error occured during setup. 
Please fix possible issues and run the script again.

`-rwxr-xr-x 1 alarm alarm  25112 Jan 28 04:14 ccnet-init`

`$ file ccnet-init 
ccnet-init: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.26, BuildID[sha1]=7e793bea760ed91e1cbc546d60e3db062bc6afb2, stripped`

`$ ./ccnet-init`
`bash: ./ccnet-init: No such file or directory`

**Comment by jobenvil** [comment]
pls check the [manual](https://manual.seafile.com/), probably user rights on directory are wrong. Did you create the user alarm in the system?

**Comment by ikwyl6** [comment]
It won't even execute the file "ccnet-init" when I try to run it by itself. It happens to all the files in that bin directory. Not a permissions things. I even tried to do a 'sudo' and executing the file and it says:

$ sudo /mnt/wd1000/BTSync/seafile/seafile-server-rpi-source-6.2.5/seafile/bin/ccnet-init
sudo: unable to execute /mnt/wd1000/BTSync/seafile/seafile-server-rpi-source-6.2.5/seafile/bin/ccnet-init: No such file or directory

I've never seen this before with any kind of file. Is there somewhere when I can download the source so I can compile these bin files?

**Comment by kvanderlaag** [comment]
I am having the same issue installing Seafile 6.25 from source on a Scaleway ARM64 server. Something is definitely weird here.

**Comment by zhangn1985** [comment]
you need to install arm runtime, prebuilt binaries are arm executable, not arm64.

**Comment by zhangn1985** [comment]
just like you have an X86-64 machine, tries to run X86 binaries, you need to install lib32*

just use `ldd ccnet-init` or other binaries, to check what missing.

**Comment by fortysix2ahead** [comment]
This also happens with the latest RPI release 6.3.4, the issue is still unresolved.

**Comment by jobenvil** [comment]
you should check the permissions as well:
```

root@hiperborea /media/sda/seafile/seafile-server-latest/seafile/bin # ll
total 1388
-rwxr-xr-x 1 seafile nogroup 233944 Okt 13  2018 ccnet-server
-rwxr-xr-x 1 seafile nogroup 563132 Okt 13  2018 seaf-server
-rwxr-xr-x 1 seafile nogroup 123856 Okt 13  2018 seaf-migrate
-rwxr-xr-x 1 seafile nogroup 126712 Okt 13  2018 seaf-fuse
-rwxr-xr-x 1 seafile nogroup 130432 Okt 13  2018 seafserv-gc
-rwxr-xr-x 1 seafile nogroup  36140 Okt 13  2018 seaf-server-init
-rwxr-xr-x 1 seafile nogroup  35320 Okt 13  2018 seafile-controller
-rwxr-xr-x 1 seafile nogroup 134528 Okt 13  2018 seaf-fsck
-rwxr-xr-x 1 seafile nogroup  22784 Okt 13  2018 ccnet-init
root@hiperborea /media/sda/seafile/seafile-server-latest/seafile/bin # ldd ccnet-init
        linux-vdso.so.1 (0xbed9f000)
        libresolv.so.2 => /lib/arm-linux-gnueabihf/libresolv.so.2 (0xb6ec1000)
        libssl.so.1.0.0 => /usr/lib/arm-linux-gnueabihf/libssl.so.1.0.0 (0xb6e76000)
        libcrypto.so.1.0.0 => /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0 (0xb6d4f000)
        libsqlite3.so.0 => /usr/lib/arm-linux-gnueabihf/libsqlite3.so.0 (0xb6ca0000)
        libevent-2.0.so.5 => /usr/lib/arm-linux-gnueabihf/libevent-2.0.so.5 (0xb6c64000)
        libuuid.so.1 => /lib/arm-linux-gnueabihf/libuuid.so.1 (0xb6c4e000)
        libsearpc.so.1 => not found
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb6c29000)
        libgio-2.0.so.0 => /usr/lib/arm-linux-gnueabihf/libgio-2.0.so.0 (0xb6b1a000)
        libgobject-2.0.so.0 => /usr/lib/arm-linux-gnueabihf/libgobject-2.0.so.0 (0xb6ad2000)
        libglib-2.0.so.0 => /usr/lib/arm-linux-gnueabihf/libglib-2.0.so.0 (0xb69f5000)
        libjansson.so.4 => /usr/lib/arm-linux-gnueabihf/libjansson.so.4 (0xb69dc000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb68e4000)
        /lib/ld-linux-armhf.so.3 (0xb6efb000)
        libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0xb68d1000)
        libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0xb6850000)
        libgmodule-2.0.so.0 => /usr/lib/arm-linux-gnueabihf/libgmodule-2.0.so.0 (0xb683d000)
        libz.so.1 => /lib/arm-linux-gnueabihf/libz.so.1 (0xb6813000)
        libselinux.so.1 => /lib/arm-linux-gnueabihf/libselinux.so.1 (0xb67ea000)
        libmount.so.1 => /lib/arm-linux-gnueabihf/libmount.so.1 (0xb67a2000)
        libffi.so.6 => /usr/lib/arm-linux-gnueabihf/libffi.so.6 (0xb678c000)
        libpcre.so.3 => /lib/arm-linux-gnueabihf/libpcre.so.3 (0xb6730000)
        libblkid.so.1 => /lib/arm-linux-gnueabihf/libblkid.so.1 (0xb66ef000)
        librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0xb66d9000)
        libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0xb66b0000)

```

**Comment by fortysix2ahead** [comment]
The install script is running as root so there should not be a permission problem.

**Comment by jobenvil** [comment]
Closing the issue due to inactivity. Please refer to [Seafile Forum](https://forum.seafile.com/) for further support.
