### ISSUE TITLE
Can't run Seahun.service as non-privileged system user

### ISSUE THREAD

**Issue by zhangn1985** [haiwen/seafile-rpi#31]
1, 使用的是此处下载的最新6.3.2
2, 操作系统：
`Linux orangepipc 4.14.18-sunxi #24 SMP Fri Feb 9 16:24:32 CET 2018 armv7l GNU/Linux`
3, 创建非特权系统用户 `sudo adduser --quiet  --system  --group  --no-create-home --disabled-password --home  /opt/seafile/ seafile`
3, 解压到运行目录: /opt/seafile/， 在以root配置后，更改所有文件所有权为seafile:seafile
4, 按照https://manual.seafile.com/deploy/start_seafile_at_system_bootup.html 设置自启动。
5, 测试服务是否能启动。

seafile.service OK
seahub.service KO

更改seahub.service的user/group为root方能正确运行。
注意：seafile.service是以非特权用户正常运行的。

在修改后，从web端登陆能下载到初始文件：`seafile-tutorial.doc`

**Comment by jobenvil** [comment]
@zhangn1985 I don't understand Chinese language, sorry. Please raise that question on Seafile Forum. https://forum.seafile.com/

**Comment by zhangn1985** [comment]
OK, sorry, I think seafile is only for Chinese, only has Chinese developer. repeat issue in english.

### Can't run Seahun.service as non-privileged system user

1, I download latest seafile from here, ver 6.3.2
2, OS:
` Linux orangepipc 4.14.18-sunxi #24 SMP Fri Feb 9 16:24:32 CET 2018 armv7l GNU/Linux`
3, create non-privileged system user:
`sudo adduser --quiet --system --group --no-create-home --disabled-password --home /opt/seafile/ seafile`
4, unzip to working path: /opt/seafile/, and configure seafile use `root` user, and them change file owner to `seafile`
5, follow this link: https://manual.seafile.com/deploy/start_seafile_at_system_bootup.html , set seafile start with system.
6, test service:

seafile.service OK
seahub.service KO

seahub.service always fail to start, unless change user/group to `root`

BTW: earything looks good, after this change, I can download `seafile-tutorial.doc` from webUI.

my question is why can't seahub.service run as non-privileged system user

**Comment by jobenvil** [comment]
Hi no issues :-) You can find further support on the [Seafile Forum](https://forum.seafile.com/) if the issue still open.
