### ISSUE TITLE
Could you please supply a link to the Documentation?

### ISSUE THREAD

**Issue by AzureIP** [haiwen/seafile-rpi#32]
Hi,
You have a real long changelog on your main site here, but I'm rather interested in an official installation and usage guide. Where can I find it?

**Comment by AzureIP** [comment]
I may correct myself. There is a normal starting site here. But the Link from the Seafile Download site is to the changelog and not to the start page. Thats confusing.

**Comment by jobenvil** [comment]
On Seafile Donwload click on "latest version" and not on "change log". See [here](https://github.com/haiwen/seafile-rpi) for further infos.

**Comment by AzureIP** [comment]
The latest version link is linking to the releases page, which is basically a changelog.
I would prefer a link to: https://github.com/haiwen/seafile-rpi

**Comment by jobenvil** [comment]
Sure? thats not a changelog that's the official GitHub Release page. The other one you pointed out is a Readme file, when you come from GitHub and not directly from Seafile Download.

**Comment by jobenvil** [comment]
The ChangeLog inside the Seafile Download page points to this link:

https://manual.seafile.com/changelog/server-changelog.html

which is the fact a ChangeLog
