### ISSUE TITLE
关于seahub_thirdpart软件库

### ISSUE THREAD

**Issue by ZidongY** [haiwen/seafile-rpi#33]
我打算编译一个树莓派 x64位的Seafile Server。
但是按照官方给出的编译手册（https://manual.seafile.com/build_seafile/server.html），经过一番折腾最终是编译出了安装包。
但是这个安装包无法正常工作。./seahub.sh start 无法正常启动，开启gunicorn daemon= False后，发现大量的错误都是在seahub的第三方软件不全上。
能否官方给出个6.3.x的第三方库列表？或者发我邮箱也可以（yinzidong2003@163.com）
谢谢！

**Comment by jobenvil** [comment]
@ZidongY If you need further support try to rise a question at [Seafile Forum](https://forum.seafile.com/). They will be glad to help you.
