### ISSUE TITLE
[question] armv7 compatibility

### ISSUE THREAD

**Issue by xifi-kif** [haiwen/seafile-rpi#35]
Hello, does this work with just raspberry-like devices or is it for any armv7 devices?

**Comment by jobenvil** [comment]
It works for any armv7 device, like OdroidXU4, Banana, etc.

**Comment by klangborste** [comment]
Yes, i also running the seafile-rpi on a Cubietruck

**Comment by xifi-kif** [comment]
Nice! Is it stable like seafile server on intel? Any truble? How long have you been running it?

**Comment by klangborste** [comment]
I use it 3 years now constantly with some updates. Works like a charm.

**Comment by klangborste** [comment]
I use it 3 years now constantly with some updates.

**Comment by xifi-kif** [comment]
Ok I'll try it!
