### ISSUE TITLE
Upgrading from 6.3.4 to 7.03 fails with  Failed to init seahub db: No module named seahub_settings.

### ISSUE THREAD

**Issue by lanmarc77** [haiwen/seafile-rpi#38]
After upgrading I get the following error message when starting seahub in seafdav.log on a RPI using Debian 9:
Failed to init seahub db: No module named seahub_settings.

I did follow the usual upgrade procedure and started the database update script 6.3 to 7.0

**Comment by jobenvil** [comment]
It's not a rpi compilation problem, moreover a [documented issue](https://forum.seafile.com/t/seafile-7-0-2-seafdav-bug-no-module-named-seahub-settings/9160). 

Despite of the error, does it work seafdav or not?

**Comment by lanmarc77** [comment]
Seafdav does not start. I applied the patch discussed in the forum but sefadav still does not start. The error message changes though: Failed to init seahub db: 'module' object has no attribute 'DATABASES'

**Comment by jobenvil** [comment]
Weird, at my end is working seafdav... despite of the erros in `seafdav.log`:
```
[2019-07-17 17:48:54,035]:  Init seahub database...
[2019-07-17 17:48:54,041]:  Failed to init seahub db: No module named seahub_settings.
```
can you check the seafdav process?
```
root@hiperborea /home/seafile/logs # ps -ef| grep -i seaf
seafile   1471     1  0 Jul17 ?        00:00:03 /media/sda/seafile/seafile-server-7.0.3/seafile/bin/seafile-controller -c /media/sda/seafile/ccnet -d /media/sda/seafile/seafile-data -F /media/sda/seafile/conf
seafile   1490     1  0 Jul17 ?        00:00:00 ccnet-server -F /media/sda/seafile/conf -c /media/sda/seafile/ccnet -f /media/sda/seafile/logs/ccnet.log -d -P /media/sda/seafile/pids/ccnet.pid
seafile   1681  1471  0 Jul17 ?        00:00:17 /usr/bin/python2.7 -m wsgidav.server.run_server --log-file /media/sda/seafile/logs/seafdav.log --pid /media/sda/seafile/pids/seafdav.pid --port 8080 --host 0.0.0.0
seafile   1695     1  0 Jul17 ?        00:00:27 seaf-server -F /media/sda/seafile/conf -c /media/sda/seafile/ccnet -d /media/sda/seafile/seafile-data -l /media/sda/seafile/logs/seafile.log -P /media/sda/seafile/pids/seaf-server.pid
seafile   2056     1  0 Jul17 ?        00:00:24 python2.7 /media/sda/seafile/seafile-server-7.0.3/seahub/thirdpart/gunicorn seahub.wsgi:application -c /media/sda/seafile/conf/gunicorn.conf --preload
seafile   2106  2056  0 Jul17 ?        00:00:02 python2.7 /media/sda/seafile/seafile-server-7.0.3/seahub/thirdpart/gunicorn seahub.wsgi:application -c /media/sda/seafile/conf/gunicorn.conf --preload
seafile   2107  2056  0 Jul17 ?        00:00:02 python2.7 /media/sda/seafile/seafile-server-7.0.3/seahub/thirdpart/gunicorn seahub.wsgi:application -c /media/sda/seafile/conf/gunicorn.conf --preload
seafile   2108  2056  0 Jul17 ?        00:00:03 python2.7 /media/sda/seafile/seafile-server-7.0.3/seahub/thirdpart/gunicorn seahub.wsgi:application -c /media/sda/seafile/conf/gunicorn.conf --preload
seafile   2109  2056  0 Jul17 ?        00:00:02 python2.7 /media/sda/seafile/seafile-server-7.0.3/seahub/thirdpart/gunicorn seahub.wsgi:application -c /media/sda/seafile/conf/gunicorn.conf --preload
seafile   2110  2056  0 Jul17 ?        00:00:03 python2.7 /media/sda/seafile/seafile-server-7.0.3/seahub/thirdpart/gunicorn seahub.wsgi:application -c /media/sda/seafile/conf/gunicorn.conf --preload
root     15657 15051  0 16:05 pts/0    00:00:00 grep --color=auto -i seaf
```

**Comment by lanmarc77** [comment]
I guess seafdav is starting, but seahub is not?
That is my console output:
```
Starting seafile server, please wait ...
** Message: seafile-controller.c(718): No seafevents.

Seafile server started

Done.

LC_ALL is not set in ENV, set to en_US.UTF-8
Starting seahub at port 8000 ...
Error:Seahub failed to start.
Please try to run "./seahub.sh start" again

seafile@seafile:~$ ps -ef| grep -i seaf
root      1539  1535  0 23:33 pts/1    00:00:00 su seafile
seafile   1540  1539  0 23:33 pts/1    00:00:00 bash
seafile   1543  1540  1 23:33 pts/1    00:00:00 mc
seafile   1545  1543  0 23:33 pts/2    00:00:00 bash -rcfile .bashrc
seafile   1594     1  0 23:33 ?        00:00:00 /home/seafile/seafile-server-7.0.3/seafile/bin/seafile-controller -c /home/seafile/ccnet -d /mnt/usb_disc/seafile-data -F /home/seafile/conf
seafile   1596     1  0 23:33 ?        00:00:00 ccnet-server -F /home/seafile/conf -c /home/seafile/ccnet -f /home/seafile/logs/ccnet.log -d -P /home/seafile/pids/ccnet.pid
seafile   1598  1594 11 23:33 ?        00:00:02 /usr/bin/python2.7 -m wsgidav.server.run_server --log-file /home/seafile/logs/seafdav.log --pid /home/seafile/pids/seafdav.pid --port 8080 --host 0.0.0.0
seafile   1599     1  0 23:33 ?        00:00:00 seaf-server -F /home/seafile/conf -c /home/seafile/ccnet -d /mnt/usb_disc/seafile-data -l /home/seafile/logs/seafile.log -P /home/seafile/pids/seaf-server.pid
seafile   1647  1545  0 23:33 pts/2    00:00:00 ps -ef
seafile   1648  1545  0 23:33 pts/2    00:00:00 grep -i seaf
seafile@seafile:~$ netstat -ltepn
(Es konnten nicht alle Prozesse identifiziert werden; Informationen über
nicht-eigene Processe werden nicht angezeigt; Root kann sie anzeigen.)
Aktive Internetverbindungen (Nur Server)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       Benutzer   Inode      PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          44108904   -
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      1000       45028875   1598/python2.7
tcp        0      0 0.0.0.0:8082            0.0.0.0:*               LISTEN      1000       45027983   1599/seaf-server
tcp6       0      0 :::22                   :::*                    LISTEN      0          44108906   -

```

**Comment by DanielEgbers** [comment]
It is not a problem with seafdav.
I do not have seafdav enabled, but I also get "**Seahub failed to start**" (and "**No seafevents**"), after upgrading from 6.3.4 to 7.0.3.

**Output of version 6.3.4:**
![image](https://user-images.githubusercontent.com/27849724/61499235-d2fe2300-a9c6-11e9-84b9-a3e44909d8ee.png)

**Output of version 7.0.3:**
![image](https://user-images.githubusercontent.com/27849724/61499268-e9a47a00-a9c6-11e9-824d-4d139a96a7b1.png)

**Logs of version 6.3.4:**
![image](https://user-images.githubusercontent.com/27849724/61500152-39387500-a9ca-11e9-9430-3dfba08569c5.png)

**Logs of version 7.0.3:**
![image](https://user-images.githubusercontent.com/27849724/61500146-2f167680-a9ca-11e9-800f-adc1720910e9.png)

**Database:**
SQLite

**System:**
Raspberry Pi 3 Model B (a02082)
Raspbian 9 / Linux 4.19.57-v7+ #1244 SMP armv7l GNU/Linux

**Comment by freeplant** [comment]
No seafevents is only message. It is not related to the problem. Can you try to start Seahub with ./seahub.sh start?

**Comment by freeplant** [comment]
"Failed to init seahub db: No module named seahub_settings."  It is only a message. WebDAV should work regardless of this message.

**Comment by jobenvil** [comment]
@lanmarc77 @DanielEgbers  Ok, if seahub fails to start, you [should do this](https://forum.seafile.com/t/where-is-seafile-server-7-ce-for-raspberry-pi/9359/4). I suppose, you probably miss the `certifi `python module. There is more support and new informations there.

**Comment by lanmarc77** [comment]
@jobenvil Spot on! I installed certifi using apt-get install python-certifi and it works.
I hope at least the manual patch finds its way into 7.0.4.

**Comment by DanielEgbers** [comment]
@jobenvil thank you. Installing python-certifi fixed it 😀

It's probably better to change "No special steps are needed" in the [release info](https://github.com/haiwen/seafile-rpi/releases/tag/v7.0.3) to something like this:
Starting from 7.0, it is mandatory to install the "python-certifi" dependence module:
```
apt-get install python-certifi
```

Please also consider adding "python-certifi" to "Prerequisites" in the [deployment docs](https://manual.seafile.com/deploy/using_sqlite.html#prerequisites)

**Comment by TT-SWP13** [comment]
Is there also a new required installation to support the seavevents package in 7.0.4?
[no module named seafevents](https://forum.seafile.com/t/no-module-named-seafevents-after-upgrade-from-seafile-rpi-6-3-4-to-7-0-4/9616?u=tt-swp13)
