### ISSUE TITLE
6.3.4 -> 7.0.3 seafile.sh fails with illegal instruction

### ISSUE THREAD

**Issue by jpsikorra** [haiwen/seafile-rpi#39]
After upgrading 6.3.4 to 7.0.3 `./seafile.sh start` fails.

`./seafile.sh: Zeile 84:  9723 Ungültiger Maschinenbefehl   LD_LIBRARY_PATH=$SEAFILE_LD_LIBRARY_PATH ${seaf_controller} --test -c "${default_ccnet_conf_dir}" -d "${seafile_data_dir}" -F "${central_config_dir}" `

Info:
`Linux raspberrypi 4.19.42+ #1219 Tue May 14 21:16:38 BST 2019 armv6l GNU/Linux`
`Python 2.7.13`

**Comment by jobenvil** [comment]
distro? `hostnamectl` output?

**Comment by jpsikorra** [comment]
hostnamectl:
Operating System: Raspbian GNU/Linux 9 (stretch)
Kernel: Linux 4.19.42+
Architecture: arm

**Comment by jpsikorra** [comment]
Maybe it is a Python dependency problem, I will check it.

**Comment by jobenvil** [comment]
No clue, sorry. Just asking if you changed the file permissions to seafile:nogroup or seafile:seafile, etc and if you did run the upgrade script. 
The python dependency problem will rise starting seahub, not seafile.

**Comment by jpsikorra** [comment]
Upgrade was successul with only the sql warnings. File permissions are seafile:nogroup.

**Comment by jobenvil** [comment]
@jpsikorra something new?

**Comment by jobenvil** [comment]
Maybe you could rise a question on the [Seafile Forum](https://forum.seafile.com/). The developers are glad to help you.

**Comment by jpsikorra** [comment]
I will try the Docker image.

**Comment by Rotzbua** [comment]
@jpsikorra Is a raspberry seafile docker file available?

**Comment by jpsikorra** [comment]
I don't know. I actually switched back to 6.3.4 for now, which seems to work fine even after the upgrade.

**Comment by jobenvil** [comment]
> I don't know. I actually switched back to 6.3.4 for now, which seems to work fine even after the upgrade.

Yes, the seafile database expansion doesn't affect the 6,3,4.
Try the help on the [Seafile Forum](https://forum.seafile.com),
