### ISSUE TITLE
Upgrade 6.3.4 to 7.0.3 - seahub does not start - no error thrown

### ISSUE THREAD

**Issue by vmario89** [haiwen/seafile-rpi#40]
Hi, i got a problem after upgrading seafile from 6.3.4 to 7.0.3 which is totally unspecific. After upgrade seahub does not start. The log file seahub.log is empty (0 byte) and journalctl -xe only shows:

> Jul 18 21:28:56 seafile-pi snoopy[1647]: [uid:1000 sid:1634 tty:(none) cwd:/ filename:/usr/bin/python2.7]: python2.7 /opt/seafile/seafile-server-7.0.3/seahub/thirdpart/gun
> Jul 18 21:28:57 seafile-pi snoopy[1650]: [uid:1000 sid:1634 tty:(none) cwd:/ filename:/bin/sleep]: sleep 5
> Jul 18 21:28:57 seafile-pi snoopy[1651]: [uid:1000 sid:1648 tty:(none) cwd:/ filename:/sbin/ldconfig]: /sbin/ldconfig -p
> Jul 18 21:28:57 seafile-pi snoopy[1653]: [uid:1000 sid:1648 tty:(none) cwd:/ filename:/bin/uname]: uname -p
> Jul 18 21:28:58 seafile-pi snoopy[1654]: [uid:1000 sid:1648 tty:(none) cwd:/ filename:/sbin/ldconfig]: /sbin/ldconfig -p
> Jul 18 21:29:02 seafile-pi snoopy[1655]: [uid:1000 sid:1634 tty:(none) cwd:/ filename:/usr/bin/pgrep]: pgrep -f seahub.wsgi:application
> Jul 18 21:29:02 seafile-pi systemd[1]: seahub.service: Main process exited, code=exited, status=1/FAILURE
> Jul 18 21:29:02 seafile-pi systemd[1]: Failed to start Seafile hub.
> Jul 18 21:29:02 seafile-pi systemd[1]: seahub.service: Unit entered failed state.
> Jul 18 21:29:02 seafile-pi systemd[1]: seahub.service: Failed with result 'exit-code'.

What i already did so far:
* run seaf-gc.sh
* run seaf-fsc.sh
* removed old pids
* checked all logs
* checked the file permissions and file owners
* updated and upgraded all libraries with apt-get
* restarted the whole raspian stretch
* double checked neccessary libs from python
* tried to start seahub in fastcgi mode instead. no chance

any idea how could i solve the problem? :-(

**Comment by vmario89** [comment]
fixed it myself. I had a wrong config of seahub.service

**Comment by jobenvil** [comment]
Mostly happens in this way. This is the magic behind to open a github issue 
Hi why not GitMate?

**Comment by vmario89** [comment]
Naah i answered too fast. It started, but ~10 seconds later it stopped working.

> -- Unit seahub.service has begun starting up.
> Jul 18 21:52:58 seafile-pi snoopy[2868]: [uid:999 sid:2868 tty:(none) cwd:/ filename:/opt/seafile/seafile-server-latest/seahub.sh]: /opt/seafile/seafile-server-latest/seah
> Jul 18 21:52:58 seafile-pi snoopy[2869]: [uid:999 sid:2868 tty:(none) cwd:/ filename:/bin/readlink]: readlink -f /opt/seafile/seafile-server-latest/seahub.sh
> Jul 18 21:52:58 seafile-pi snoopy[2870]: [uid:999 sid:2868 tty:(none) cwd:/ filename:/usr/bin/dirname]: dirname /opt/seafile/seafile-server-7.0.3/seahub.sh
> Jul 18 21:52:58 seafile-pi snoopy[2871]: [uid:999 sid:2868 tty:(none) cwd:/ filename:/usr/bin/dirname]: dirname /opt/seafile/seafile-server-7.0.3
> Jul 18 21:52:58 seafile-pi snoopy[2872]: [uid:999 sid:2868 tty:(none) cwd:/ filename:/usr/bin/which]: which python2.7
> Jul 18 21:52:58 seafile-pi snoopy[2873]: [uid:999 sid:2868 tty:(none) cwd:/ filename:/bin/cat]: cat /opt/seafile/ccnet/seafile.ini
> Jul 18 21:52:58 seafile-pi seahub.sh[2868]: LC_ALL is not set in ENV, set to en_US.UTF-8
> Jul 18 21:52:58 seafile-pi snoopy[2874]: [uid:999 sid:2868 tty:(none) cwd:/ filename:/usr/bin/pgrep]: pgrep -f seafile-controller -c /opt/seafile/ccnet
> Jul 18 21:52:58 seafile-pi snoopy[2875]: [uid:999 sid:2868 tty:(none) cwd:/ filename:/usr/bin/pgrep]: pgrep -f /opt/seafile/seafile-server-7.0.3/seahub/manage.py
> Jul 18 21:52:58 seafile-pi snoopy[2876]: [uid:999 sid:2868 tty:(none) cwd:/ filename:/usr/bin/pgrep]: pgrep -f seahub.wsgi:application
> Jul 18 21:52:58 seafile-pi snoopy[2877]: [uid:999 sid:2868 tty:(none) cwd:/ filename:/bin/mkdir]: mkdir -p /opt/seafile/logs
> Jul 18 21:52:58 seafile-pi seahub.sh[2868]: Starting seahub at port 8000 ...
> Jul 18 21:52:58 seafile-pi snoopy[2878]: [uid:999 sid:2868 tty:(none) cwd:/ filename:/usr/bin/python2.7]: python2.7 /opt/seafile/seafile-server-7.0.3/check_init_admin.py
> Jul 18 21:52:59 seafile-pi snoopy[2879]: [uid:999 sid:2868 tty:(none) cwd:/ filename:/sbin/ldconfig]: /sbin/ldconfig -p
> Jul 18 21:52:59 seafile-pi snoopy[2881]: [uid:999 sid:2868 tty:(none) cwd:/ filename:/usr/bin/python2.7]: python2.7 /opt/seafile/seafile-server-7.0.3/seahub/thirdpart/guni
> Jul 18 21:53:00 seafile-pi snoopy[2884]: [uid:999 sid:2868 tty:(none) cwd:/ filename:/bin/sleep]: sleep 5
> Jul 18 21:53:00 seafile-pi snoopy[2885]: [uid:999 sid:2882 tty:(none) cwd:/ filename:/sbin/ldconfig]: /sbin/ldconfig -p
> Jul 18 21:53:00 seafile-pi snoopy[2887]: [uid:999 sid:2882 tty:(none) cwd:/ filename:/bin/uname]: uname -p
> Jul 18 21:53:00 seafile-pi snoopy[2888]: [uid:999 sid:2882 tty:(none) cwd:/ filename:/sbin/ldconfig]: /sbin/ldconfig -p
> Jul 18 21:53:05 seafile-pi snoopy[2889]: [uid:999 sid:2868 tty:(none) cwd:/ filename:/usr/bin/pgrep]: pgrep -f seahub.wsgi:application
> Jul 18 21:53:05 seafile-pi seahub.sh[2868]: Error:Seahub failed to start.
> Jul 18 21:53:05 seafile-pi seahub.sh[2868]: Please try to run "./seahub.sh start" again
> Jul 18 21:53:05 seafile-pi systemd[1]: seahub.service: Control process exited, code=exited status=1
> Jul 18 21:53:05 seafile-pi systemd[1]: Failed to start Seafile hub.
> -- Subject: Unit seahub.service has failed
> -- Defined-By: systemd
> -- Support: https://www.debian.org/support
> --
> -- Unit seahub.service has failed.

**Comment by jobenvil** [comment]
You will find the solution here: https://forum.seafile.com/t/where-is-seafile-server-7-ce-for-raspberry-pi/9359/8

**Comment by jobenvil** [comment]
keyword: `Demon = False`

**Comment by vmario89** [comment]
the installation of libs fixed it. Lack of documentation in official guides at the moment

**Comment by jobenvil** [comment]
The [official stablished communication channel  for Seafile Raspberry Pi](https://github.com/haiwen/seafile-rpi#reporting-issues--github-issues) is defined under reporting issues.  

The community support that you got was best effort and in that case, even helped you.
