### ISSUE TITLE
Consistent naming scheme

### ISSUE THREAD

**Issue by BernieO** [haiwen/seafile-rpi#42]
First of all thanks for your very reliable work in compiling Seafile for ARM!

However, to be able to automate upgrades with a script, it would be helpful to have a consistent naming scheme. Compared to previous versions, for version 7.0.4 there is the string „_stable“ in the filename missing, which breaks scripts like:
https://github.com/klangborste/seafile_rpi_bash_upgrader

Would it be possible to use a consistent naming scheme in the future?

**Comment by jhonny-oliveira** [comment]
I share the same remark for the same reason.
Anyways, many thanks for your work!

**Comment by jobenvil** [comment]
Appreciated guys, i left deliberately this time the stable remark. I though that was not necessary anymore... and was not aware of such scripts. Thanks for feedback. Will change it.

**Comment by BernieO** [comment]
Thanks for implementing the suggestion :+1:

**Comment by jobenvil** [comment]
@BernieO Be aware that the naming convention was changed staring with v7.1.5. This was necessary. Sorry for the inconveniencies.

**Comment by jobenvil** [comment]
@jhonny-oliveira Be aware that the naming convention was changed staring with v7.1.5. This was necessary. Sorry for the inconveniencies.
