### ISSUE TITLE
./setup-seafile.sh: line 517:   323 Illegal instruction

### ISSUE THREAD

**Issue by xrv0** [haiwen/seafile-rpi#43]
Generating ccnet configuration in /home/pi/ccnet...

./setup-seafile.sh: line 517:   323 Illegal instruction     LD_LIBRARY_PATH=$SEAFILE_LD_LIBRARY_PATH "${ccnet_init}" -F "${default_conf_dir}" -c "${default_ccnet_conf_dir}" --name "${server_name}" --host "${ip_or_domain}"

Error occured during setup. 
Please fix possible issues and run the script again.

Im running Raspbian 10 buster on a Pi B+ and using the latest stable version

**Comment by Rotzbua** [comment]
search helps #41
