### ISSUE TITLE
Failed to sync seafile database

### ISSUE THREAD

**Issue by jonneymendoza** [haiwen/seafile-rpi#49]
Hi i keep get this error whenever i try and setup the latest seafile-rpi server which is 7.0.5

When i specify the data location path to my exfat ext hdd connected to my pi4 and then continue on to installing sea file. i get this error

```Seahub is the web interface for seafile server.
Now let's setup seahub configuration. Press [ENTER] to continue
-----------------------------------------------------------------


Creating database now, it may take one minute, please wait...

/home/me/temp/seafile-server-7.0.5
Failed to sync seafile database.


Error occured during setup.
Please fix possible issues and run the script again.
```

**Comment by schellenberg** [comment]
Same error. In my case, a cifs mounted drive.

**Comment by jonneymendoza** [comment]
anyone can help?

**Comment by shoeper** [comment]
Use ext{3,4}, btrfs, zfs or xfs - at least for the install dir. The data can still be in another location.

**Comment by zen42** [comment]
Just ran into this as well. On a hunch I moved the install folder (so seafile-server-xxx) onto the filesystem i was installing to and accepted the scripts path suggestion. Everything worked file after that.

As to why this happening i spent 5 mins looking into it and found nothing. Maybe something with the sqllite3 .read going across filesystems?

**Comment by jonneymendoza** [comment]
ive given up on seafile. the support is none existant and the software itself is very buggy

**Comment by thrynir** [comment]
Hi,

As @shoeper said, you should not use exfat. It's a Microsoft proprietary filesystem. Linux don't handle it well.
Microsoft recently allow the community to use exfat by set it open source. But it haven't been merged into linux kernel yet.

You should use ext4 for less bug and best performance.

**Comment by JojOatXGME** [comment]
It looks like there is a bug in the `setup-seafile.sh`. Maybe the following change would fix the issue.

```diff
- seafile_db=${TOPDIR}/seafile-data/seafile.db
+ seafile_db=${seafile_data_dir}/seafile.db
  seafile_sql=${INSTALLPATH}/sql/sqlite/seafile.sql
  if ! sqlite3 ${seafile_db} ".read ${seafile_sql}" 2>/dev/null 1>&2; then
    echo "Failed to sync seafile database."
    err_and_quit;
  fi
```

Otherwise, you might need to create a `seafile-data` directory next to the seafile installation.

**Comment by Tommy-LXDAO** [comment]
> It looks like there is a bug in the `setup-seafile.sh`. Maybe the following change would fix the issue.
> 
> ```diff
> - seafile_db=${TOPDIR}/seafile-data/seafile.db
> + seafile_db=${seafile_data_dir}/seafile.db
>   seafile_sql=${INSTALLPATH}/sql/sqlite/seafile.sql
>   if ! sqlite3 ${seafile_db} ".read ${seafile_sql}" 2>/dev/null 1>&2; then
>     echo "Failed to sync seafile database."
>     err_and_quit;
>   fi
> ```
> 
> Otherwise, you might need to create a `seafile-data` directory next to the seafile installation.

nice idea! I have solved my problem! Thank you very much!

**Comment by jobenvil** [comment]
@JojOatXGME and @ll I will close and pin this issue, since this is still not amended on upstream code.
