### ISSUE TITLE
When I start Seahub, It Report an error "No module named 'ccnet'"

### ISSUE THREAD

**Issue by DavinciEvans** [haiwen/seafile-rpi#59]
My vehicle is Respberry 4B, and the system is raspbian buster. 

I first use `./setup-seafile.sh` to set up seafile, and then `./seafile.sh start` is also Operating normally. when I enter `./seahub.sh start`, Python report this error. So what is the problem? Thanks you a lot. (Please forgive my poor Engilsh : )
![QQ截图20200702002719](https://user-images.githubusercontent.com/45795384/86268490-da7c0380-bbfa-11ea-8bef-a9a9c8e337ba.png)

**Comment by jobenvil** [comment]
@DavinciEvans don't bother about your english, mine is not better :-)

I recommend you to go the following [thread in the Seafile forum](https://forum.seafile.com/t/seafile-server-7-1-4-for-raspberry-pi-is-ready-23-05-2020/11945). You will find the solution there. You can search in the forum for "ModuleNotFoundError: No module named 'ccnet'.

**Comment by DavinciEvans** [comment]
> @DavinciEvans don't bother about your english, mine is not better :-)
> 
> I recommend you to go the following [thread in the Seafile forum](https://forum.seafile.com/t/seafile-server-7-1-4-for-raspberry-pi-is-ready-23-05-2020/11945). You will find the solution there. You can search in the forum for "ModuleNotFoundError: No module named 'ccnet'.

Thanks! This problem was solved in a nice way!
