### ISSUE TITLE
The name of shared libraries or folders appears always as None.

### ISSUE THREAD

**Issue by dlgltlzed** [haiwen/seafile-rpi#6]

**Comment by langhaarschneider** [comment]
Same Problem here with Server 4.2.2 on BananaPi
(I always use the raspberryPI version of seafile without any issues)

**Comment by der-domi** [comment]
Is that something like this:
https://forum.seafile-server.org/t/geteilte-bibliotheken-ohne-beschriftung/1694

rmarkdev built the latest version of seafile-rpi. Maybe it fixed this issue? Can you test it (with a test environment)?
https://github.com/rmarkdev/seafile-rpi/releases

**Comment by langhaarschneider** [comment]
Thank you - i upgraded to rmarkdev's 4.2.3-built - and i see the names again!

**Comment by jobenvil** [comment]
Hello langhaarschneider, for future bugs, infos & updates check the Seafile Forum; i.e. [here](https://forum.seafile-server.org/t/server-4-2-3-for-rpi/1984). Usually the rpi/arm version appears after two weeks the Seafile Server version for generic Linux is published.
