### ISSUE TITLE
树莓派安装seafile时出现问题

### ISSUE THREAD

**Issue by iGmainC** [haiwen/seafile-rpi#63]
在运行`setup-seafile.sh`时出现如下错误：
```
Generating ccnet configuration in /usr/local/lib/ccnet...

./setup-seafile.sh:行467: /usr/local/lib/seafile-server/seafile/bin/ccnet-init: 没有那个文件或目录


Error occured during setup.
Please fix possible issues and run the script again.
```
但是该文件是存在的，也给了权限
```
  文件：/usr/local/lib/seafile-server/seafile/bin/ccnet-init
  大小：18344           块：40         IO 块：4096   普通文件
设备：b302h/45826d      Inode：3111708     硬链接：1
权限：(0777/-rwxrwxrwx)  Uid：(    0/    root)   Gid：(    0/    root)
最近访问：2020-08-01 14:23:18.541895651 +0800
最近更改：2020-08-01 14:16:13.679215865 +0800
最近改动：2020-08-01 14:22:43.338757640 +0800
创建时间：2020-08-01 14:16:13.679215865 +0800
```

系统使用的是Manjaro-arm

求助，该如何解决

**Comment by iGmainC** [comment]
根据测试，按照官方论坛中 [树莓派3B+部署seafile7.1.4(使用 MySQL/MariaDB)](https://bbs.seafile.com/t/topic/12360) 进行操作，树莓派版Ubuntu-server也会出现这种情况，希望官方解答

**Comment by jobenvil** [comment]
The issue is already commented on the official Seafile support forum:

https://forum.seafile.com/

**Comment by cm9vdA** [comment]
这种情况是因为你的系统里缺少ccnet-init需要链接的动态库
使用readelf -d 可以看到它需要的动态库，你对照着找找看看缺了哪个。

**Comment by iGmainC** [comment]
> 这种情况是因为你的系统里缺少ccnet-init需要链接的动态库
> 使用readelf -d 可以看到它需要的动态库，你对照着找找看看缺了哪个。

我这里测试是因为ccnet-init是32位，我自行编译64位seafile-rpi后这个点可以过去，后面的组件又出问题了

**Comment by CralBenz** [comment]
什么原因，在线等
root@raspberrypi:/home/pi/seafile-server-8.0.3# ./seafile.sh start

Starting seafile server, please wait ...
/home/pi/seafile-server-8.0.3/seafile/bin/seafile-controller: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.25' not found (required by /home/pi/seafile-server-8.0.3/seafile/lib/libcrypto.so.1.1)
/home/pi/seafile-server-8.0.3/seafile/bin/seafile-controller: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.25' not found (required by /home/pi/seafile-server-8.0.3/seafile/lib/libuuid.so.1)
Failed to start seafile server

**Comment by jobenvil** [comment]
I assume the issue has gone. Closing.
