### ISSUE TITLE
最新版没有cent的包么？

### ISSUE THREAD

**Issue by fengchuisaman** [haiwen/seafile-rpi#73]
我看了一下release 最近的安装包没有cent的。官方是以后不支持了么？我自认为cent还是挺多人使用的吧。

**Comment by jobenvil** [comment]
Here the [last status](https://cloud.seatable.io/dtable/external-links/a85d4221e41344c19566/?tid=0000&vid=0000) and supported releases/distros. [Seafile Forum](https://forum.seafile.com/) is your friend.
