### ISSUE TITLE
nothing for noobs

### ISSUE THREAD

**Issue by user239393** [haiwen/seafile-rpi#74]
i can install nextcloud, pihole, a raspberry over ssh. but no chance for me to install seafile and get it to run. it is to complicated.

this is to short
$ wget https://raw.githubusercontent.com/haiwen/seafile-rpi/master/build3.sh
$ chmod u+x build3.sh
$ ./build3.sh 8.0.0

**Comment by framps** [comment]
@user239393 Have you seen [this page](https://github.com/haiwen/seafile-rpi/releases) ?

**Comment by shoeper** [comment]
So now your $software has a database failure. What are you doing?

**Comment by VooDisss** [comment]
i agree, i have been trying to install this seafile on my rpi 3b+ armv7 FOR THREE DAYS, I HAVE BEEN TRYING ALOT OF TIMES ALL OVER (from flashing raspi os) and it just does not freaking work, why no one can make a step by step easy copy paste commands from installing raspi os?
@framps

**Comment by jobenvil** [comment]
https://forum.seafile.com/ and https://manual.seafile.com/ are your best friends for the next time you decide to try it out again.
