### ISSUE TITLE
depens on libselinux.so.1

### ISSUE THREAD

**Issue by igraltist** [haiwen/seafile-rpi#8]
/usr/src/seafile/seafile-server-4.3.1/seafile/bin/ccnet-init: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory

I have gentoo running and no selinux. Is there an easy fix?

**Comment by jobenvil** [comment]
Maybe this can help you:

https://github.com/haiwen/seafile/issues/219
http://www.linuxquestions.org/questions/slackware-14/trying-to-install-seafile-need-libselinux-so-1-a-4175530553/

but probably you already read it. I'm just building up for debian/armhf6. Maybe Lins05 or freeplant can help you...
