### ISSUE TITLE
LDAP disabled in build ?

### ISSUE THREAD

**Issue by Josue-T** [haiwen/seafile-rpi#81]
Hello,

Following [this discussion](https://forum.seafile.com/t/ldap-broken-under-seafile-8-0-1-server/13526/13) I suspect that LDAP is disabled in the build for version 8.0. Can we check this ?

**Comment by jobenvil** [comment]
Yes, it was disabled and [enabled again](https://forum.seafile.com/t/ldap-broken-under-seafile-8-0-1-server/13526/30). Should work now. Closing.
