### ISSUE TITLE
这是什么原因，大神们

### ISSUE THREAD

**Issue by CralBenz** [haiwen/seafile-rpi#82]
什么原因
root@raspberrypi:/home/pi/seafile-server-8.0.3# ./seafile.sh start

Starting seafile server, please wait ...
/home/pi/seafile-server-8.0.3/seafile/bin/seafile-controller: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.25' not found (required by /home/pi/seafile-server-8.0.3/seafile/lib/libcrypto.so.1.1)
/home/pi/seafile-server-8.0.3/seafile/bin/seafile-controller: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.25' not found (required by /home/pi/seafile-server-8.0.3/seafile/lib/libuuid.so.1)
Failed to start seafile server

**Comment by jobenvil** [comment]
This error could have many reasons but mostly is because you choosed the wrong distro version. In any case for the next time you can post questions, issues on the Seafile Forum.
