### ISSUE TITLE
Which server version to use for ubuntu server installation on a RaspberryPi 4B

### ISSUE THREAD

**Issue by sorenoneill** [haiwen/seafile-rpi#90]
I'm getting this error when running seafile.sh start:

`# ./seafile.sh: line 114: /srv/seafile/seafile/bin/seafile-controller: cannot execute binary file: Exec format error`

I've installed an ubuntu server 20.04 on a raspberry pi 4b -- I thus downloaded the 64 bit 8.0.7 seafile server generic for linux

Should I have installed the seafile server for raspberry pi instead?

```
$ uname -a
Linux ubuntu 5.4.0-1042-raspi #46-Ubuntu SMP PREEMPT Fri Jul 30 00:35:40 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

$ cat /proc/cpuinfo 
processor	: 0
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 1
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 2
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 3
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

Hardware	: BCM2835
Revision	: d03114
Serial		: 100000007ffd81c1
Model		: Raspberry Pi 4 Model B Rev 1.4
```

**Comment by jobenvil** [comment]
> Should I have installed the seafile server for raspberry pi instead?

Yes, that is the case. Take the armv8(x64) version.

**Comment by sorenoneill** [comment]
Hmm... that seems to have dependencies not in Ubuntu server 20.04.3 -- e.g. python-mysql  (python3-mysqldb is installed)

Is the raspberry version of seafile built on Raspbian ?

**Comment by sorenoneill** [comment]
Hmm package dependency issues ... pymysql module not installed

which version of python is seafile 8.0.7 expecting?

**Comment by jobenvil** [comment]
It expects a higher python version than 3.5. https://forum.seafile.com/, https://manual.seafile.com. WHich modules do you need, it is explained there.

**Comment by jobenvil** [comment]
@sorenoneill I see you joined the forum and issue got solved, closing then...
