### ISSUE TITLE
Seafile is not for noobs, forget it and go for nextcloud

### ISSUE THREAD

**Issue by VooDisss** [haiwen/seafile-rpi#92]
Why nobody can just do a full tutorial (command to paste list) how to get seafile to work after installing raspi OS?
im stuck at it showing me "welcome to your swag instance" when it should finally give me the login page of seafile.
Im salty as hell over the wasted time (talking about DAYS) installing this thing on my rpi 3b+ armv7

**Comment by jobenvil** [comment]
@VooDisss Stop posting rage opinions. GitHub is not a forum place. Go to the [Seafile forum]([url](https://forum.seafile.com/)) to rise your concerns, so the people can you help you. Read before post is a good approach. See: https://github.com/haiwen/seafile-rpi#reporting-issues--github-issues

**Comment by jobenvil** [comment]
@VooDisss If you try it out again, consume information from https://manual.seafile.com/ to deploy the seafile application and https://forum.seafile.com/ to ask for support.
