### ISSUE TITLE
seahub failed to start after upgrading to Raspbian Bullseye

### ISSUE THREAD

**Issue by es-ka** [haiwen/seafile-rpi#95]
```
$ ./seahub.sh start-fastcgi

LC_ALL is not set in ENV, set to en_US.UTF-8
./seahub.sh: Zeile 210: Warnung: setlocale: LC_ALL: Kann die Regionseinstellungen nicht ändern (en_US.UTF-8): Datei oder Verzeichnis nicht gefunden
Starting seahub (fastcgi) at 127.0.0.1:8000 ...
Traceback (most recent call last):
  File "/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/MySQLdb/__init__.py", line 18, in <module>
    from . import _mysql
ImportError: cannot import name '_mysql' from partially initialized module 'MySQLdb' (most likely due to a circular import) (/opt/seafile/seafile-server-8.0.3/seahub/thirdpart/MySQLdb/__init__.py)
```

Is there a way to fix this or do I have to wait for a dedicated "bullseye" realease?

**Comment by Gustl22** [comment]
Fast cgi has been dropped:
https://forum.seafile.com/t/so-fast-cgi-has-been-dropped-is-there-a-chapter-in-the-manual-how-to-migrate/7561

Also can browse these builds ( not released yet, as new Golang fileserver is not included yet, but works as before without, only arm64 builds):
https://cloud.reb0.org/d/3a3af571a79e4d62a11b/

Consider running the update scripts accordingly.

**Comment by es-ka** [comment]
Well, I didn't use fcgi. But I couldn't find any other way to show error messages on startup of seahub at all. (Maybe a lack in official install docs...)
Meanwhile I found out to set `daemon = false` in `conf/gunicorn.conf` which is also not mentioned in https://manual.seafile.com/config/ The error concerning mysql import remains, so I guess it isn't fcgi related.

Thanks for the link, but I can't test these builds because I use armv7l.

**Comment by Gustl22** [comment]
Sorry then have to be patient. Builds for new distros such as Bullseye will be included in the next rpi release :)

**Comment by es-ka** [comment]
OK, thanks for clarification.

**Comment by es-ka** [comment]
Just upgraded to 9.0.2 from https://cloud.reb0.org/d/3a3af571a79e4d62a11b/files/?p=%2Fseafile-server-9.0.2%2Fseafile-server-9.0.2-bullseye-arm32v7l.tar.gz
Works for me.

**Comment by jobenvil** [comment]
@es-ka I assume I can close the issue, isn't it? Starting from now there will be support for Bullseye distro.
